# Generated by Django 6.0.5 on 2026-06-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100, verbose_name='Name (DE)')),
                ('name_ua', models.CharField(max_length=100, verbose_name='Назва (UA)')),
                ('slug', models.SlugField(help_text='Unic', unique=True)),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
            },
        ),
        migrations.CreateModel(
            name='CleaningDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Anfang der Woche')),
                ('date_end', models.DateField(verbose_name='Ende der Woche')),
                ('room_number', models.CharField(choices=[('waiting', 'Warten(Очикування)'), ('done', 'Geputzt(Прибрано)'), ('failed', 'Nicht geputzt(Не прибрано)')], default='waiting', max_length=20, verbose_name='Status')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cleaningarea')),
            ],
            options={
                'verbose_name': 'Duty',
                'verbose_name_plural': 'Duties',
                'ordering': ['date_start', 'date_end', 'area'],
            },
        ),
    ]
