# Generated by Django 6.0.5 on 2026-06-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_cleaningarea_cleaningduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningduty',
            name='status',
            field=models.CharField(choices=[('waiting', 'Warten(Очикування)'), ('done', 'Geputzt(Прибрано)'), ('failed', 'Nicht geputzt(Не прибрано)')], default='waiting', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cleaningduty',
            name='room_number',
            field=models.CharField(max_length=20, verbose_name='Room number'),
        ),
    ]
