# Generated by Django 6.0.5 on 2026-06-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_cleaningduty_status_alter_cleaningduty_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AnnouncementComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comments')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.announcement')),
            ],
        ),
    ]
