# Generated by Django 6.0.5 on 2026-06-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_announcement_owner_announcementcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
    ]
